title: Rudzainy Rahman
description: Personal website of Rudzainy Rahman
theme: just-the-docs

url: https://rudzainy.github.io

aux_links:
  Let's work together!: https://rudzainy.github.io/contact

paginate: 5
