title: Rudzainy Rahman
description: Personal website of Rudzainy Rahman
theme: just-the-docs

url: https://rudzainy.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
